spring:
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.DriverSpy
      password: 1q2w3e4r!!
      username: root
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/baseball_records?useSSL=false&serverTimezone=UTC

  autoconfigure:
    exclude:
#            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfilguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  templates:
    prefix: file:src/main/resources/templates/
  resources:
    static-locations: file:src/main/resources/static/
  freemarker:
    cache: false
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

server:
  port: 9990
  servlet:
    context-path: /